package com.thundax.kuzhambu.knowledge.application.graph.command;

public record RequestGraphExtractionCommand(
        String scopeType,
        String scopeJson,
        String triggerSource,
        String selectionScopeJson,
        Boolean replaceUnconfirmedOnly,
        Long parentTaskId,
        String sourceContentType,
        Long sourceContentId,
        Long requestedBy,
        Long serviceId,
        String serviceRole,
        Long modelId,
        String modelName,
        Long promptVersionId,
        String requestId,
        String traceId,
        String promptMessagesJson,
        String promptVariablesJson,
        String promptHash,
        String inputPayloadJson,
        String outputSchemaJson,
        boolean forceJson,
        String locale) {}
