SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `ai_model` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `api_source` varchar(32) NOT NULL,
    `base_url` varchar(512) NOT NULL,
    `encrypted_api_key` varchar(2048) DEFAULT NULL,
    `model_name` varchar(255) NOT NULL,
    `display_name` varchar(255) NOT NULL,
    `capabilities_json` json NOT NULL,
    `default_params_json` json DEFAULT NULL,
    `description` varchar(1024) DEFAULT NULL,
    `enabled` tinyint(1) NOT NULL DEFAULT 1,
    `registered_at` datetime(3) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_model_source_name` (`api_source`, `model_name`),
    KEY `idx_ai_model_enabled` (`api_source`, `enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI模型表';

CREATE TABLE IF NOT EXISTS `ai_business_config` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `capability` varchar(64) NOT NULL,
    `prompt_template_id` bigint NOT NULL,
    `model_id` bigint NOT NULL,
    `default_params_json` json DEFAULT NULL,
    `enabled` tinyint(1) NOT NULL DEFAULT 1,
    `configured_at` datetime(3) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_business_config_capability` (`capability`),
    KEY `idx_ai_business_config_prompt` (`prompt_template_id`),
    KEY `idx_ai_business_config_model` (`model_id`),
    KEY `idx_ai_business_config_enabled` (`enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI业务配置表';

CREATE TABLE IF NOT EXISTS `ai_prompt_template` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `capability` varchar(64) NOT NULL,
    `name` varchar(255) NOT NULL,
    `description` varchar(1024) DEFAULT NULL,
    `enabled` tinyint(1) NOT NULL DEFAULT 1,
    `current_version_no` int DEFAULT NULL,
    `registered_at` datetime(3) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_prompt_template_capability` (`capability`),
    KEY `idx_ai_prompt_template_enabled` (`enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI提示词模板表';

CREATE TABLE IF NOT EXISTS `ai_prompt_version` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `template_id` bigint NOT NULL,
    `version_no` int NOT NULL,
    `message_templates_json` json NOT NULL,
    `variables_snapshot_json` json NOT NULL,
    `output_schema_json` json DEFAULT NULL,
    `change_summary` varchar(512) DEFAULT NULL,
    `registered_at` datetime(3) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_prompt_version_no` (`template_id`, `version_no`),
    KEY `idx_ai_prompt_version_template` (`template_id`, `registered_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI提示词版本表';

CREATE TABLE IF NOT EXISTS `ai_prompt_variable` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `template_id` bigint NOT NULL,
    `variable_name` varchar(128) NOT NULL,
    `required` tinyint(1) NOT NULL DEFAULT 1,
    `description` varchar(512) DEFAULT NULL,
    `priority` int NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_prompt_variable_name` (`template_id`, `variable_name`),
    UNIQUE KEY `uk_ai_prompt_variable_priority` (`priority`),
    KEY `idx_ai_prompt_variable_template` (`template_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI提示词变量表';

CREATE TABLE IF NOT EXISTS `ai_call_record` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `call_id` bigint NOT NULL,
    `batch_id` bigint DEFAULT NULL,
    `scope` varchar(32) DEFAULT NULL,
    `capability` varchar(64) NOT NULL,
    `content_type` varchar(32) DEFAULT NULL,
    `content_id` bigint DEFAULT NULL,
    `object_id` bigint DEFAULT NULL,
    `service_id` bigint DEFAULT NULL,
    `service_role` varchar(16) DEFAULT NULL,
    `model_id` bigint DEFAULT NULL,
    `model_name` varchar(255) DEFAULT NULL,
    `prompt_version_id` bigint DEFAULT NULL,
    `request_id` varchar(128) DEFAULT NULL,
    `trace_id` varchar(128) DEFAULT NULL,
    `status` varchar(16) NOT NULL DEFAULT 'RUNNING',
    `stream_used` tinyint(1) NOT NULL DEFAULT 0,
    `stream_completed` tinyint(1) NOT NULL DEFAULT 0,
    `fallback_used` tinyint(1) NOT NULL DEFAULT 0,
    `latency_ms` int DEFAULT NULL,
    `input_tokens` int NOT NULL DEFAULT 0,
    `output_tokens` int NOT NULL DEFAULT 0,
    `cost_amount` decimal(18, 6) NOT NULL DEFAULT 0.000000,
    `failure_stage` varchar(64) DEFAULT NULL,
    `result_format` varchar(32) DEFAULT NULL,
    `result_payload` longtext DEFAULT NULL,
    `artifact_reference_json` json DEFAULT NULL,
    `error_type` varchar(32) DEFAULT NULL,
    `error_message` varchar(1024) DEFAULT NULL,
    `warnings_json` json DEFAULT NULL,
    `requested_at` datetime(3) NOT NULL,
    `completed_at` datetime(3) DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_call_record_id` (`call_id`),
    KEY `idx_ai_call_record_batch` (`batch_id`, `status`),
    KEY `idx_ai_call_record_target` (`content_type`, `content_id`, `capability`),
    KEY `idx_ai_call_record_status` (`status`, `requested_at`),
    KEY `idx_ai_call_record_trace` (`trace_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI调用记录表';

CREATE TABLE IF NOT EXISTS `ai_candidate` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `candidate_id` bigint NOT NULL,
    `call_id` bigint DEFAULT NULL,
    `batch_id` bigint DEFAULT NULL,
    `capability` varchar(64) NOT NULL,
    `content_type` varchar(32) NOT NULL,
    `content_id` bigint NOT NULL,
    `object_id` bigint DEFAULT NULL,
    `result_format` varchar(32) NOT NULL,
    `result_payload` longtext DEFAULT NULL,
    `status` varchar(16) NOT NULL DEFAULT 'PENDING',
    `artifact_reference_json` json DEFAULT NULL,
    `failure_stage` varchar(64) DEFAULT NULL,
    `prompt_version_id` bigint DEFAULT NULL,
    `model_name` varchar(255) DEFAULT NULL,
    `error_type` varchar(32) DEFAULT NULL,
    `error_message` varchar(1024) DEFAULT NULL,
    `requested_at` datetime(3) NOT NULL,
    `applied_at` datetime(3) DEFAULT NULL,
    `rejected_at` datetime(3) DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_candidate_id` (`candidate_id`),
    KEY `idx_ai_candidate_target` (`content_type`, `content_id`, `capability`),
    KEY `idx_ai_candidate_batch` (`batch_id`, `status`),
    KEY `idx_ai_candidate_call` (`call_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI候选结果表';

CREATE TABLE IF NOT EXISTS `ai_refinement_task` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `task_id` bigint NOT NULL,
    `scope` varchar(32) DEFAULT NULL,
    `capability` varchar(64) NOT NULL,
    `content_type` varchar(32) NOT NULL,
    `content_id` bigint NOT NULL,
    `object_id` bigint DEFAULT NULL,
    `requested_by` bigint NOT NULL,
    `request_id` varchar(128) DEFAULT NULL,
    `trace_id` varchar(128) DEFAULT NULL,
    `status` varchar(32) NOT NULL DEFAULT 'PENDING',
    `service_role` varchar(16) DEFAULT NULL,
    `model_id` bigint DEFAULT NULL,
    `model_name` varchar(255) DEFAULT NULL,
    `prompt_version_id` bigint DEFAULT NULL,
    `call_id` bigint DEFAULT NULL,
    `candidate_id` bigint DEFAULT NULL,
    `result_format` varchar(32) DEFAULT NULL,
    `result_preview` text DEFAULT NULL,
    `failure_stage` varchar(32) DEFAULT NULL,
    `error_type` varchar(64) DEFAULT NULL,
    `error_message` text DEFAULT NULL,
    `stream_enabled` tinyint(1) NOT NULL DEFAULT 0,
    `requested_at` datetime(3) NOT NULL,
    `started_at` datetime(3) DEFAULT NULL,
    `completed_at` datetime(3) DEFAULT NULL,
    `cancelled_at` datetime(3) DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_refinement_task_id` (`task_id`),
    KEY `idx_ai_refinement_task_status` (`status`, `requested_at`),
    KEY `idx_ai_refinement_task_target` (`content_type`, `content_id`, `capability`),
    KEY `idx_ai_refinement_task_requested_by` (`requested_by`, `requested_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI精修任务台账表';

CREATE TABLE IF NOT EXISTS `ai_batch_job` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `batch_id` bigint NOT NULL,
    `scope` varchar(32) DEFAULT NULL,
    `capability` varchar(64) NOT NULL,
    `content_type` varchar(32) NOT NULL,
    `status` varchar(32) NOT NULL DEFAULT 'RUNNING',
    `total_count` int NOT NULL DEFAULT 0,
    `success_count` int NOT NULL DEFAULT 0,
    `failed_count` int NOT NULL DEFAULT 0,
    `cancelled_count` int NOT NULL DEFAULT 0,
    `failure_summary_json` json DEFAULT NULL,
    `requested_at` datetime(3) NOT NULL,
    `cancelled_at` datetime(3) DEFAULT NULL,
    `completed_at` datetime(3) DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_batch_job_id` (`batch_id`),
    KEY `idx_ai_batch_job_status` (`status`, `requested_at`),
    KEY `idx_ai_batch_job_capability` (`content_type`, `capability`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI批量任务表';

CREATE TABLE IF NOT EXISTS `ai_image_understanding` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `understanding_id` bigint NOT NULL,
    `storage_object_id` bigint NOT NULL,
    `content_hash` varchar(128) NOT NULL,
    `analysis_markdown` longtext NOT NULL,
    `call_id` bigint DEFAULT NULL,
    `prompt_version_id` bigint DEFAULT NULL,
    `model_name` varchar(255) DEFAULT NULL,
    `requested_at` datetime(3) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_image_understanding_id` (`understanding_id`),
    UNIQUE KEY `uk_ai_image_understanding_object_hash` (`storage_object_id`, `content_hash`),
    KEY `idx_ai_image_understanding_hash` (`content_hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI图片理解结果表';

CREATE TABLE IF NOT EXISTS `ai_entry_split_candidate` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `split_candidate_id` bigint NOT NULL,
    `candidate_id` bigint NOT NULL,
    `parent_content_type` varchar(32) NOT NULL,
    `parent_content_id` bigint NOT NULL,
    `title` varchar(255) NOT NULL,
    `original_text` longtext NOT NULL,
    `translation_text` longtext DEFAULT NULL,
    `target_volume_id` bigint DEFAULT NULL,
    `priority` int NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_entry_split_candidate_id` (`split_candidate_id`),
    UNIQUE KEY `uk_ai_entry_split_candidate_priority` (`priority`),
    KEY `idx_ai_entry_split_candidate_parent` (`parent_content_type`, `parent_content_id`),
    KEY `idx_ai_entry_split_candidate_candidate` (`candidate_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI条目拆分候选表';
