SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `ai_model` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `api_source` varchar(32) NOT NULL,
    `base_url` varchar(512) NOT NULL,
    `encrypted_api_key` varchar(2048) DEFAULT NULL,
    `model_name` varchar(255) NOT NULL,
    `display_name` varchar(255) NOT NULL,
    `capabilities_json` json NOT NULL,
    `default_params_json` json DEFAULT NULL,
    `description` varchar(1024) DEFAULT NULL,
    `enabled` tinyint(1) NOT NULL DEFAULT 1,
    `registered_at` datetime(3) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_model_source_name` (`api_source`, `model_name`),
    KEY `idx_ai_model_enabled` (`api_source`, `enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI模型表';

CREATE TABLE IF NOT EXISTS `ai_business_config` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `capability` varchar(64) NOT NULL,
    `prompt_template_id` bigint NOT NULL,
    `model_id` bigint NOT NULL,
    `default_params_json` json DEFAULT NULL,
    `enabled` tinyint(1) NOT NULL DEFAULT 1,
    `priority` int NOT NULL DEFAULT 0,
    `configured_at` datetime(3) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_business_config_priority` (`priority`),
    KEY `idx_ai_business_config_capability` (`capability`, `enabled`),
    KEY `idx_ai_business_config_prompt` (`prompt_template_id`),
    KEY `idx_ai_business_config_model` (`model_id`),
    KEY `idx_ai_business_config_enabled` (`enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI业务配置表';

CREATE TABLE IF NOT EXISTS `ai_prompt_template` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `capability` varchar(64) NOT NULL,
    `name` varchar(255) NOT NULL,
    `description` varchar(1024) DEFAULT NULL,
    `enabled` tinyint(1) NOT NULL DEFAULT 1,
    `current_version_no` int DEFAULT NULL,
    `registered_at` datetime(3) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_prompt_template_capability` (`capability`),
    KEY `idx_ai_prompt_template_enabled` (`enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI提示词模板表';

CREATE TABLE IF NOT EXISTS `ai_prompt_version` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `template_id` bigint NOT NULL,
    `version_no` int NOT NULL,
    `message_templates_json` json NOT NULL,
    `variables_snapshot_json` json NOT NULL,
    `output_schema_json` json DEFAULT NULL,
    `change_summary` varchar(512) DEFAULT NULL,
    `registered_at` datetime(3) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_prompt_version_no` (`template_id`, `version_no`),
    KEY `idx_ai_prompt_version_template` (`template_id`, `registered_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI提示词版本表';

CREATE TABLE IF NOT EXISTS `ai_prompt_variable` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `template_id` bigint NOT NULL,
    `variable_name` varchar(128) NOT NULL,
    `required` tinyint(1) NOT NULL DEFAULT 1,
    `description` varchar(512) DEFAULT NULL,
    `priority` int NOT NULL COMMENT 'AI域全局唯一排序权重，不按template_id重新编号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_prompt_variable_name` (`template_id`, `variable_name`),
    UNIQUE KEY `uk_ai_prompt_variable_priority` (`priority`),
    KEY `idx_ai_prompt_variable_template` (`template_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI提示词变量表';

CREATE TABLE IF NOT EXISTS `ai_invocation_log` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'AI调用日志数据库主键',
    `call_id` bigint NOT NULL COMMENT 'AI调用日志业务ID，对外关联候选结果、任务和业务trace',
    `batch_id` bigint DEFAULT NULL COMMENT '批量任务业务ID，对应ai_batch_job.id，单次调用为空',
    `scope` varchar(32) DEFAULT NULL COMMENT '调用来源业务域或运行范围',
    `capability` varchar(64) NOT NULL COMMENT '本次调用使用的AI业务能力',
    `content_type` varchar(32) DEFAULT NULL COMMENT '被处理业务内容类型',
    `content_id` bigint DEFAULT NULL COMMENT '被处理业务内容ID',
    `object_id` bigint DEFAULT NULL COMMENT '被处理内容下的细分对象ID',
    `service_id` bigint DEFAULT NULL COMMENT '发起调用的AI服务配置ID',
    `service_role` varchar(16) DEFAULT NULL COMMENT '发起调用的AI服务角色',
    `model_id` bigint DEFAULT NULL COMMENT '实际使用的AI模型配置ID',
    `model_name` varchar(255) DEFAULT NULL COMMENT '实际使用的AI模型名称快照',
    `prompt_version_id` bigint DEFAULT NULL COMMENT '实际使用的提示词版本ID',
    `request_id` varchar(128) DEFAULT NULL COMMENT '调用请求ID，用于幂等和排查',
    `trace_id` varchar(128) DEFAULT NULL COMMENT '调用链路追踪ID',
    `status` varchar(16) NOT NULL DEFAULT 'RUNNING' COMMENT '调用状态：RUNNING/SUCCEEDED/FAILED',
    `stream_used` tinyint(1) NOT NULL DEFAULT 0 COMMENT '本次调用是否使用流式输出',
    `stream_completed` tinyint(1) NOT NULL DEFAULT 0 COMMENT '流式调用是否收到完成事件',
    `fallback_used` tinyint(1) NOT NULL DEFAULT 0 COMMENT '本次调用是否使用降级路径',
    `latency_ms` int DEFAULT NULL COMMENT '调用耗时毫秒数',
    `input_tokens` int NOT NULL DEFAULT 0 COMMENT '输入token数量',
    `output_tokens` int NOT NULL DEFAULT 0 COMMENT '输出token数量',
    `cost_amount` decimal(18, 6) NOT NULL DEFAULT 0.000000 COMMENT '本次调用成本金额快照',
    `failure_stage` varchar(64) DEFAULT NULL COMMENT '失败发生阶段',
    `result_format` varchar(32) DEFAULT NULL COMMENT '结果格式，例如TEXT/JSON/ARTIFACT',
    `result_payload` longtext DEFAULT NULL COMMENT '调用最终结果内容或对象存储结果引用',
    `artifact_reference_json` json DEFAULT NULL COMMENT 'worker返回的原始 artifact 引用信息',
    `error_type` varchar(32) DEFAULT NULL COMMENT '失败类型',
    `error_message` varchar(1024) DEFAULT NULL COMMENT '失败说明',
    `warnings_json` json DEFAULT NULL COMMENT 'worker返回的非阻断告警',
    `requested_at` datetime(3) NOT NULL COMMENT '调用发起时间',
    `completed_at` datetime(3) DEFAULT NULL COMMENT '调用完成时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_invocation_log_id` (`call_id`),
    KEY `idx_ai_invocation_log_batch` (`batch_id`, `status`),
    KEY `idx_ai_invocation_log_target` (`content_type`, `content_id`, `capability`),
    KEY `idx_ai_invocation_log_status` (`status`, `requested_at`),
    KEY `idx_ai_invocation_log_trace` (`trace_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI调用结构化日志表，记录每次worker调用的请求、模型、结果、成本和错误，用于审计、排查和报表';

CREATE TABLE IF NOT EXISTS `ai_candidate` (
    `id` bigint NOT NULL COMMENT 'AI候选结果业务ID，对外作为candidateId使用',
    `call_id` bigint DEFAULT NULL COMMENT '生成该候选结果的AI调用日志业务ID，对应ai_invocation_log.call_id',
    `batch_id` bigint DEFAULT NULL COMMENT '批量任务业务ID，对应ai_batch_job.id，单次候选为空',
    `capability` varchar(64) NOT NULL COMMENT '生成该候选结果使用的AI业务能力',
    `content_type` varchar(32) NOT NULL COMMENT '候选结果所属业务内容类型',
    `content_id` bigint NOT NULL COMMENT '候选结果所属业务内容ID',
    `object_id` bigint DEFAULT NULL COMMENT '候选结果所属内容下的细分目标对象ID',
    `result_format` varchar(32) NOT NULL COMMENT '候选结果格式，例如TEXT/JSON/ARTIFACT',
    `result_payload` longtext DEFAULT NULL COMMENT '候选结果内容或对象存储结果引用',
    `status` varchar(16) NOT NULL DEFAULT 'PENDING' COMMENT '候选结果状态：PENDING/APPLIED/REJECTED',
    `artifact_reference_json` json DEFAULT NULL COMMENT 'worker返回的原始 artifact 引用信息',
    `failure_stage` varchar(64) DEFAULT NULL COMMENT '候选生成失败发生阶段',
    `prompt_version_id` bigint DEFAULT NULL COMMENT '生成候选使用的提示词版本ID',
    `model_name` varchar(255) DEFAULT NULL COMMENT '生成候选使用的AI模型名称快照',
    `error_type` varchar(32) DEFAULT NULL COMMENT '候选生成或处理失败类型',
    `error_message` varchar(1024) DEFAULT NULL COMMENT '候选生成或处理失败说明',
    `requested_at` datetime(3) NOT NULL COMMENT '候选生成请求时间',
    `applied_at` datetime(3) DEFAULT NULL COMMENT '候选被应用到正式业务数据的时间',
    `rejected_at` datetime(3) DEFAULT NULL COMMENT '候选被拒绝的时间',
    PRIMARY KEY (`id`),
    KEY `idx_ai_candidate_target` (`content_type`, `content_id`, `capability`),
    KEY `idx_ai_candidate_batch` (`batch_id`, `status`),
    KEY `idx_ai_candidate_call` (`call_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI候选结果表';

CREATE TABLE IF NOT EXISTS `ai_refinement_task` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `task_id` bigint NOT NULL,
    `scope` varchar(32) DEFAULT NULL,
    `capability` varchar(64) NOT NULL,
    `content_type` varchar(32) NOT NULL,
    `content_id` bigint NOT NULL,
    `object_id` bigint DEFAULT NULL,
    `requested_by` bigint NOT NULL,
    `request_id` varchar(128) DEFAULT NULL,
    `trace_id` varchar(128) DEFAULT NULL,
    `status` varchar(32) NOT NULL DEFAULT 'PENDING',
    `service_role` varchar(16) DEFAULT NULL,
    `model_id` bigint DEFAULT NULL,
    `model_name` varchar(255) DEFAULT NULL,
    `prompt_version_id` bigint DEFAULT NULL,
    `call_id` bigint DEFAULT NULL,
    `candidate_id` bigint DEFAULT NULL,
    `result_format` varchar(32) DEFAULT NULL,
    `result_preview` text DEFAULT NULL,
    `failure_stage` varchar(32) DEFAULT NULL,
    `error_type` varchar(64) DEFAULT NULL,
    `error_message` text DEFAULT NULL,
    `stream_enabled` tinyint(1) NOT NULL DEFAULT 0,
    `requested_at` datetime(3) NOT NULL,
    `started_at` datetime(3) DEFAULT NULL,
    `completed_at` datetime(3) DEFAULT NULL,
    `cancelled_at` datetime(3) DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_refinement_task_id` (`task_id`),
    KEY `idx_ai_refinement_task_status` (`status`, `requested_at`),
    KEY `idx_ai_refinement_task_target` (`content_type`, `content_id`, `capability`),
    KEY `idx_ai_refinement_task_requested_by` (`requested_by`, `requested_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI精修任务台账表';

CREATE TABLE IF NOT EXISTS `ai_batch_job` (
    `id` bigint NOT NULL COMMENT 'AI批量任务业务ID，对外作为batchId使用',
    `scope` varchar(32) DEFAULT NULL COMMENT '批量任务所属业务域或运行范围',
    `capability` varchar(64) NOT NULL COMMENT '批量任务处理的AI业务能力',
    `content_type` varchar(32) NOT NULL COMMENT '批量任务处理的业务内容类型',
    `status` varchar(32) NOT NULL DEFAULT 'RUNNING' COMMENT '批量任务状态：RUNNING/SUCCEEDED/PARTIAL/CANCELLED',
    `total_count` int NOT NULL DEFAULT 0 COMMENT '批量任务总单元数量',
    `success_count` int NOT NULL DEFAULT 0 COMMENT '批量任务成功单元数量',
    `failed_count` int NOT NULL DEFAULT 0 COMMENT '批量任务失败单元数量',
    `cancelled_count` int NOT NULL DEFAULT 0 COMMENT '批量任务取消单元数量',
    `failure_summary_json` json DEFAULT NULL COMMENT '批量任务失败摘要JSON',
    `requested_at` datetime(3) NOT NULL COMMENT '批量任务创建时间',
    `cancelled_at` datetime(3) DEFAULT NULL COMMENT '批量任务取消时间',
    `completed_at` datetime(3) DEFAULT NULL COMMENT '批量任务完成时间',
    PRIMARY KEY (`id`),
    KEY `idx_ai_batch_job_status` (`status`, `requested_at`),
    KEY `idx_ai_batch_job_capability` (`content_type`, `capability`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI批量任务表';

CREATE TABLE IF NOT EXISTS `ai_image_understanding` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `understanding_id` bigint NOT NULL,
    `storage_object_id` bigint NOT NULL,
    `content_hash` varchar(128) NOT NULL,
    `analysis_markdown` longtext NOT NULL,
    `call_id` bigint DEFAULT NULL,
    `prompt_version_id` bigint DEFAULT NULL,
    `model_name` varchar(255) DEFAULT NULL,
    `requested_at` datetime(3) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_image_understanding_id` (`understanding_id`),
    UNIQUE KEY `uk_ai_image_understanding_object_hash` (`storage_object_id`, `content_hash`),
    KEY `idx_ai_image_understanding_hash` (`content_hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI图片理解结果表';

CREATE TABLE IF NOT EXISTS `ai_entry_split_candidate` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `split_candidate_id` bigint NOT NULL,
    `candidate_id` bigint NOT NULL,
    `parent_content_type` varchar(32) NOT NULL,
    `parent_content_id` bigint NOT NULL,
    `title` varchar(255) NOT NULL,
    `original_text` longtext NOT NULL,
    `translation_text` longtext DEFAULT NULL,
    `target_volume_id` bigint DEFAULT NULL,
    `priority` int NOT NULL COMMENT 'AI域全局唯一排序权重，不按candidate_id重新编号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_entry_split_candidate_id` (`split_candidate_id`),
    UNIQUE KEY `uk_ai_entry_split_candidate_priority` (`priority`),
    KEY `idx_ai_entry_split_candidate_parent` (`parent_content_type`, `parent_content_id`),
    KEY `idx_ai_entry_split_candidate_candidate` (`candidate_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI条目拆分候选表';
