"""Stable internal service path allowlists."""

AI_USECASE_PATHS = (
    "/internal/ai/classics/sancai/translate",
    "/internal/ai/classics/sancai/translate-batch-item",
    "/internal/ai/classics/sancai/summary",
    "/internal/ai/classics/sancai/tags",
    "/internal/ai/classics/sancai/qa",
    "/internal/ai/classics/sancai/image-analysis",
    "/internal/ai/classics/sancai/fusion",
    "/internal/ai/classics/sancai/visual-description",
    "/internal/ai/classics/sancai/image-gen",
    "/internal/ai/classics/sancai/split",
    "/internal/ai/classics/wangqi/summary",
    "/internal/ai/classics/wangqi/tags",
    "/internal/ai/classics/wangqi/qa",
    "/internal/ai/classics/ming-customs/summary",
    "/internal/ai/classics/ming-customs/tags",
    "/internal/ai/classics/ming-customs/qa",
    "/internal/ai/discovery/query-understanding",
    "/internal/ai/discovery/query-rewrite",
    "/internal/ai/discovery/answer-generation",
    "/internal/ai/discovery/answer-generation/stream",
    "/internal/ai/knowledge/relation-extraction",
    "/internal/ai/knowledge/graph-extraction",
    "/internal/ai/knowledge/lineage-extraction",
    "/internal/ai/knowledge/tag-extraction",
    "/internal/ai/platform/prompt-suggestion",
    "/internal/ai/platform/version-summary",
)
